application: coden
version: snippet
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (.*/\.svn/.*)|
 (.*\.py[co])|
 (.*/Thumbs\.db)|
 )$

default_expiration: "3650d"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /.*
  script: main.py